export const BUSINESS_CATEGORY_OPTIONS = [
  "Agriculture Products",
  "Art & Crafts",
  "Baby Products",
  "Bags & Luggage",
  "Bakery & Homemade Food",
  "Beauty & Personal Care",
  "Books & Stationery",
  "Clothing & Apparel",
  "Computers & Accessories",
  "Dairy Products",
  "Decor & Handicrafts",
  "Electronics",
  "Fashion Accessories",
  "Footwear",
  "Furniture",
  "Gifts & Personalized Products",
  "Grocery & Essentials",
  "Health & Nutrition",
  "Home & Kitchen",
  "Home Decor",
  "Industrial Supplies",
  "Jewellery",
  "Kitchen Appliances",
  "Lifestyle Products",
  "Mobile Phones & Accessories",
  "Nursery & Gardening",
  "Organic Products",
  "Pet Supplies",
  "Religious / Puja Items",
  "Refurbished Products",
  "Sports & Fitness Equipment",
  "Stationery Supplies",
  "Toys & Games",
  "Vehicle Accessories",
  "Watches",
  "Wellness Products",
  "Other",
] as const;

export type BusinessCategoryOption = (typeof BUSINESS_CATEGORY_OPTIONS)[number];
